version: "3.9"

services:
  # client:
  #   image: client
  #   build: ./client
  #   container_name: react-app
  #   depends_on:
  #     - server
  #   ports:
  #     - "3000:3000"
  #   stdin_open: true
  #   tty: true
  #   networks:
  #     - transcendence_net

  # server:
  #   container_name: nest-api
  #   image: server
  #   build: ./server
  #   depends_on:
  #     - db
  #   restart : always
  #   ports:
  #     - "3001:3001"
  #     - "5555:5555"
  #   env_file:
  #     - .env 
  #   networks:
  #     - transcendence_net

  db:
    image: postgres:15.2-alpine
    container_name: db
    restart : always
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - transcendence_net

networks:
  transcendence_net:

volumes:
  pg_data: